### ISSUE TITLE
Link for testing OIDC provider is broken (README)

### ISSUE THREAD

**Issue by DevasenaInupakutika** [rohe/fedlab#12]
The [link](http://openidtest.uninett.no) for testing OIDC provider seems to be broken. Could you please update README with correct working URL?

Thanks!

**Comment by rohe** [comment]
> 21 apr. 2016 kl. 13:05 skrev Devasena Inupakutika (di1c13) <notifications@github.com>:
> 
> The link for testing OIDC provider seems to be broken. Could you please update README with correct working URL?

That link hasn’t work in years !

This is the one you should use:

https://op.certification.openid.net:60000

There you can register your OP and start testing.

— Roland

”I posit that life is better when you possess a sustaining practice that holds your desire, demands your attention, and requires effort; a plot of ground that gratifies the wish to labor and create — and, by so doing, to rule over an imagined world of your own.” - Anna Malamud Smith

**Comment by DevasenaInupakutika** [comment]
Thank you! That works!
